@api = http://localhost:3000/task


GET {{api}}

###

GET {{api}}/1

###

GET {{api}}/count


###

POST {{api}}
Content-Type: application/json

{
    "title":"6 task",
    "description":"create new app"
}

###

DELETE {{api}}/4


###
PUT {{api}}/1
Content-Type: application/json

{
    "title":"5 task",
    "description":"create new app"
}
